### ISSUE TITLE
Server side vehicle spawning

### ISSUE THREAD

**Issue by glefave0209** [fkk-cz/noire-public#652] opened 2022-03-07 19:07 UTC
Can we have somewhere to park when we are working sanitation so the vehicles don't disappear?

**Comment by fkk-cz** [comment] 2022-03-09 01:57
Vehicle despawning is most likely caused by the server being unable to migrate a client spawned vehicle to another player. An attempt was made to fix this months ago by spawning vehicles server-side, unfortunately, this caused tremendous svSync hitching due to some entity buildup (all the vehicles that would have normally despawned).

Another attempt will be made once we migrate hosts in the near future.

**Comment by fkk-cz** [comment] 2022-03-24 04:50
Trying server side vehicle creation _again in_ https://github.com/fkk-cz/noire/commit/ee58c305f433b202f4630e1faded65bd1d168da5. Let's hope it doesn't cause the entity buildup issue from months ago which resulted in unbearable svSync hitching.

Will only apply to vehicles spawned from a personal garage, if people could give feedback on this that would be appreciated.

**Comment by fkk-cz** [comment] 2022-04-01 04:27
Vehicles created server-side _still_ seem to despawn, for some unknown reason. Tried a contrived test last week which demonstrated the issue:

- Spawn in the vehicle from a personal garage
- Park the vehicle in a remote area with no one in my client's network range
- Teleport away and verify the server has ownership of the vehicle
- Teleport back and verify the vehicle is still there
- Repeat a few times
- On one occasion, entity ownership was not migrated to the server or any player (verified with netobjviewer) and was deleted.

Added vehicle creation/deletion debug logging to hopefully determine the cause of this.

**Comment by fkk-cz** [comment] 2022-04-07 01:51
Update:

For some reason, certain vehicles are marked as no-longer-needed when the vehicle is deleted. No idea what causes this as no client script is currently calling any of the SetxXxAsNoLongerNeeded natives.

One edge case I've noticed exists where teleporting out of a moving vehicle in network range of other players will cause the vehicle to reset back to an initial state (incorrect license plate, no vehicle upgrades, etc). This is unlikely to happen in the course of normal player behavior, and was forced by purposely teleporting out of the vehicle to another player.

Another issue is vehicles will _still_ sometimes despawn, probably related to the reason above.

**Comment by fkk-cz** [comment] 2022-04-19 03:53
Forgot to give an update here - all vehicles spawned at both public and personal garages are now created server-side. Cars will no longer despawn unless explicitly deleted by the server (using admin/restricted commands).

**Closed by fkk-cz** 2022-04-19 03:53 UTC
Labels: enhancement, further investigation required
