### ISSUE TITLE
[BUG]: Dog Walking bug persisting.

### ISSUE THREAD

**Issue by FARQ3X** [fkk-cz/noire-public#1300] opened 2023-03-09 05:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://streamable.com/5rq3e1
https://streamable.com/g8rwth
https://streamable.com/t45bkh

### Expected Behavior

It should pay me, happens more and more the closer you get to Tsunami as said before, script buildup of some kind?

### Steps To Reproduce

Dog walk

### Anything else?

The distance thing being increased helped with a few other bugs, still doesnt pay you on occasion. I got 2/4 clips tonight but Ill get more over the coming days, maybe you guys will be able to figure it out with more content!

**Comment by FARQ3X** [comment] 2023-03-09 13:56
https://streamable.com/ssttc0

**Comment by FARQ3X** [comment] 2023-03-14 23:09
Ok! So have had it happen a whole lot recently with the server timeout issues, but ive found a common denominator! Whenever the dog walk isnt going to pay sometime during the walk, the dog will randomly stop following the player, and follow a player that gets close to it, while players bugging the dog out when they are close is nothing new, the last 5 that didn't pay have all happened when the dog at one point or another Locked On to follow another player and had to be kicked to start following the Dog Walker again.

**Comment by fkk-cz** [comment] 2023-06-26 04:07
> the dog will randomly stop following the player, and follow a player that gets close to it

This was caused by bad task handling logic that didn't properly handle or account for a different player being the netowner of the animal ped. Should be fixed by explictly requesting control & exempting the ped from request filtering.

**Closed** 2023-06-27 00:52 UTC
Labels: bug
