### ISSUE TITLE
DOJ bug

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire-public#1231] opened 2022-11-27 05:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever I’m clocked in it shows that court is closed. A large amount of the time.

100% of the time since maybe Sunday or Monday of last week it does not send anyone who pleads not guilty to court whenever it’s open. 

And then, if I have to re-charge someone and they press not guilty, they do not come to court whenever court is open as well  

fly ins are not coming whenever court is open. Court possibly currently is listed as open right now but it’s actually closed.

### Expected Behavior

Just for court to be able to function where it shows that it’s open and people are taking their properly. 

### Steps To Reproduce

You would clocked in as judge and then send someone off to jail while clocked in as judge. They press not guilty, and they do not show up in the court cells.

### Anything else?

Thank you for the help. I’ve been monitoring it for the last week.

**Comment by JakeBurns23** [comment] 2022-11-27 19:01
This needs fixed, if not fixed soon once it is fixed the court is going to be so overrun from all the people that need to handle charges.

Also as a state attorney I enjoy my job and this is hindering every aspect of my job.

Plz Fix 🙏

**Comment by fkk-cz** [comment] 2022-11-30 04:56
This issue was caused by a mismatch in the increment/decrement logic for the `judge` job, specifically inconsistent ranks being used in the setJob/playerDropped handlers. Fixed in https://github.com/fkk-cz/noire/commit/dfbdd33095f8392546bb5d7433001c989f1504b9.

**Closed by fkk-cz** 2022-11-30 04:56 UTC
