### ISSUE TITLE
Gas Station Issue

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire-public#925] opened 2022-06-14 22:44 UTC
I tried to start a gas run and it only spawned the Trailer not the truck! it took the money for the run also! https://medal.tv/games/gta-v/clips/ovjlmqGuEvlBn/d1337QPQq62i?invite=cr-MSxiUUEsMTg3OTQ2MDQs

**Comment by fkk-cz** [comment] 2022-06-20 10:51
Duplicate of https://github.com/fkk-cz/noire-public/issues/907.

**Closed by fkk-cz** 2022-06-20 10:51 UTC
Labels: duplicate, wontfix
