### ISSUE TITLE
<AUTO THEFT MISSION ISSUE>

### ISSUE THREAD

**Issue by KamD23** [fkk-cz/noire-public#1209] opened 2022-10-18 21:34 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

this bug appears to be with the ending of the Auto Theft Missions.

- perform a hotwire on the vehicle.
- wait the designated time for the handler to give a destinated drop off locations
- on delivery of the vehicle to the designated location the mission just ends, and no dirty money is acquired for the mission.

-requires me to cancel the "current mission" to claim a new mission.
-has occurred 3 times in a row with no payout and the vehicle still being available to drive around

### Expected Behavior

the Auto Theft is supposed to work as the following:

- perform a hotwire on the vehicle.
- wait the designated time for the handler to give a destination drop off locations
- on deliver of the vehicle to the designated location the car will forcibly stop moving and kick you out of the vehicle.
- upon being kicked out the vehicle and you run a few meters away from the vehicle then the vehicle disappears.
- once disappeared you get a payout and notification stating mission complete across the screen.

### Steps To Reproduce

- Go to a mechanic shop in and talk to the handler to acquire an Auto Theft Mission
- go to circled area on the map of the vehicle location, to find the desired vehicle
- perform a hotwire on the vehicle.
- wait the designated time for the handler to give a destination drop off locations
- on delivery of the vehicle to the designated location the mission just ends, and no dirty money is acquired for the mission.

This has occurred three times claiming a new Auto Theft Mission and repeating the above steps for the same outcome to occur

### Anything else?

The video saved of the issue happening is on my third Auto Theft mission of this "completion" not paying 

attached is a twitter link to the video showing the issue, the video was to large to attach.

https://twitter.com/WetBreadLover1/status/1582484615109160966?s=20&t=hSk5FDBTxjEXktlMH000FQ

This issue doesn't occur every day but happens more often than it should, with the number of cops required to even attempt makes it hard to do these as often as I would like so I try to take advantage when possible. Completing 3 of these missions with no pay definitely should be checked out to ensure when the missions are available it makes it worth attempting.

(edit) 10/20/2022
Lastly, recently I have been only getting cars located in the MRPD station garage with no possible way to enter it also eliminates the whole mission to be even possible.

**Comment by fkk-cz** [comment] 2022-10-20 11:32
I was unable to reproduce this issue with those steps you listed above. There was an issue with the mission completion where a validity check would fail for some unknown reason. This was fixed in https://github.com/fkk-cz/noire/commit/d1486f62124395d7fb42b4bdb7d71fc9923d1e06.

Logs today showed no players having issues with turning in vehicles, waiting to see if there's any further issues.

**Comment by fkk-cz** [comment] 2022-10-22 22:12
Looks like this issue is resolved. Haven't seen any errors since 10/20 when the change was pushed.

**Closed by fkk-cz** 2022-10-22 22:12 UTC
Labels: bug, pending
