### ISSUE TITLE
New Promoter job 

### ISSUE THREAD

**Issue by TheBottomFragger** [fkk-cz/noire-public#1099] opened 2022-08-08 12:13 UTC
Soooo.. the new promoter job is a bit buggy, which I get since it’s a new job. BUT I thought I would mention it either way:
Some of the jobs don’t actually give out money AND sometimes the job bugs out, so you have to fly out and fly back in to find a job again. 

seems like there’s 2 ppl that got their jobs bugged on the third job. I don’t know if this is intentional or not, but thought I would mention it.

**Comment by TheBottomFragger** [comment] 2022-08-08 15:07
Update: 
It’s not just the third one that bugs out, cause it seems like two of us had issues with the first job. We press E, but nothing happened .

**Comment by TheBottomFragger** [comment] 2022-08-08 15:24
AND I know that sometimes you struggle to recreate the problem, so I got a clip for you in case that happens again:
https://medal.tv/games/gta-v/clips/vO9GxtekYtVtH/fldCrwE5SRtt?invite=cr-MSwyNGosMjEyMDU2NTAs

**Comment by fkk-cz** [comment] 2022-08-08 20:20
> It’s not just the third one that bugs out, cause it seems like two of us had issues with the first job. We press E, but nothing happened .

Were you in proximity of another player while attempting to place the poster?

Does the no payout bug happen after a successful animation?

**Comment by TheBottomFragger** [comment] 2022-08-08 20:27
> > It’s not just the third one that bugs out, cause it seems like two of us had issues with the first job. We press E, but nothing happened .
> 
> Were you in proximity of another player while attempting to place the poster?
> 
> Does the no payout bug happen after a successful animation?

I tried out at least 6 jobs where there was no animation, and no one nearby. Wasn’t able to try out the job once. I know that it was somewhat working for a few people right after restart, BUT after that I’m pretty sure it hasn’t worked for anyone. I put in a clip, don’t know if you saw it, but there’s literally no animation. I tried to go into the circle from different angles, but I don’t think that has anything to do with it lmao

**Comment by fkk-cz** [comment] 2022-08-08 21:57
The marker and corresponding input logic is all client-side and isn't the issue here. If no animation is playing or payout isn't being received properly that means some check in a server script is failing. I'll look into this.

**Comment by TheBottomFragger** [comment] 2022-08-08 21:58
> The marker and corresponding input logic is all client-side and isn't the issue here. If no animation is playing or payout isn't being received properly that means some check in a server script is failing. I'll look into this.

Awesome, thanks

**Comment by fkk-cz** [comment] 2022-08-09 07:53
One of the checks in the poster placement event was failing because the corresponding entry in the poster table wasn't being cleared when the job would reset (after approx. 15-20 mins). Fixed in https://github.com/fkk-cz/noire/commit/f51254bc58a2d8f3616f3c6d2695965d80741345.

**Comment by TheBottomFragger** [comment] 2022-08-09 12:28
Seems like the job is still very buggy. 
-If there’s already a poster on the wall, you won’t be able to put one over, but this only happens sometimes. So it will still let you put up another poster right away on some locations. 
-Some of the posters don’t get put up until like up to 10 minutes later, so if you’re driving away from the location because you think the job is bugged, it will take you out of your vehicle and teleport you to the location.

**Comment by cxerq** [comment] 2022-08-09 13:17
Here is a clip of it bugging out then teleporting to the job! I never actually left the area but you can get an idea of whats happening, I recreate it just do the job and eventually it will happen! https://streamable.com/69n9dv

**Comment by fkk-cz** [comment] 2022-08-09 18:46
> Here is a clip of it bugging out then teleporting to the job! I never actually left the area but you can get an idea of whats happening, I recreate it just do the job and eventually it will happen! https://streamable.com/69n9dv

I don't see any teleporting in this? Only thing that stands out is the gray poster that shouldn't be there prior to placement, and a longer than expected delay before the task starts. I'll try the job later and see what I can come up with.

**Comment by cxerq** [comment] 2022-08-09 18:48
> 

thats cause i didnt clip when i teleported, So basically if you get that poster that kinda goes into the wall and you leave it will teleport, Ill get a better clip so you can see exactly what i mean

**Comment by noyeahsure** [comment] 2022-08-09 18:51
I just did a job, first job went great, second job went to the placement, hit E to place, nothing happened, sat there for a few minutes, ended up going on DOT and the yellow place circle was still there as well

**Comment by TheBottomFragger** [comment] 2022-08-09 19:07
Same happened to me, first job went great, second job got fucked. I went to the circle, pressed E, and then the whole thing bugged. Adding a clip:
https://medal.tv/games/gta-v/clips/vX6JphHhIpZOW/d1337UPNWKLE?invite=cr-MSxPcUYsMjEyMDU2NTAs

**Comment by fkk-cz** [comment] 2022-08-10 00:11
This is probably caused by the client waiting indefinitely for network ownership -- which, for some reason, isn't being transferred to the player that's standing right next to the object. Added a server check to delay the client callback until the ownership is at least transferred to _some_ client, and removed the client wait for ownership.

Dealing with networked entity creation surely leads to issues like these. Of course, none of these appear in my limited testing environment, everything seems to work fine in a local environment. Thanks for pointing these issues out, hopefully this will be the last fix needed. https://github.com/fkk-cz/noire/commit/525818e6b7b6f49b0905bce3c5937daf6dac0de7

**Comment by cxerq** [comment] 2022-08-10 14:55
Would it be possible to add a way to cancel a mission, Cause if you and someone else the get same job it can only be done one time and the other person can do anything!

**Comment by cxerq** [comment] 2022-08-10 15:21
Now it is a rare case that would happen, So its not a big deal at all, But when the server is at full capacity and it starts happening people would have to relog to fix it, Or maybe if you just change jobs it will auto cancel any active job so just changing jobs could fix it!

**Comment by fkk-cz** [comment] 2022-08-12 10:38
> Now it is a rare case that would happen, So its not a big deal at all, But when the server is at full capacity and it starts happening people would have to relog to fix it, Or maybe if you just change jobs it will auto cancel any active job so just changing jobs could fix it!

That's a race condition, added a check to back out and allow new job searching if you somehow happen to receive a job that already has a valid poster object. https://github.com/fkk-cz/noire/commit/c501d321a416fa1553f02b5a5fd710d4a144c081

**Closed by fkk-cz** 2022-08-12 10:38 UTC
Labels: bug, pending
