### ISSUE TITLE
Issues with voice chat since server change

### ISSUE THREAD

**Issue by Mynameisnotlenny** [fkk-cz/noire-public#857] opened 2022-05-19 22:00 UTC
Hey, ever since the servers were moved yesterday I have been having higher ping and packet loss within the server. I’m not able to speak to people without my voice cutting out however I can hear others perfectly fine.

**Comment by YeetMeAway** [comment] 2022-05-19 23:15
While my ping and PL have been lower, I have had the same voice issue, while i test my mic in monitoring software and it sounds clear.  When i speak in city it is very choppy to others at times

**Comment by fkk-cz** [comment] 2022-05-20 04:14
> I have been having higher ping and packet loss within the server.

'Higher ping' is most likely caused by an increased geographic distance from your client to the server.

The packet loss indicator in `cl_drawPerf` is not entirely accurate either.

Not sure what is causing the Mumble issue -- what region are you guys in?

**Comment by YeetMeAway** [comment] 2022-05-20 04:18
I connect from near Detroit. Had 1 person from Canada and Another from Australia sound fine to everyone and I was bugged to them but in all monitoring software and tests I ran my mic came through fine.

**Comment by Mynameisnotlenny** [comment] 2022-05-20 04:19
I’m in Toronto for reference

**Comment by Mynameisnotlenny** [comment] 2022-05-20 08:19
Changed some security settings within my router and that has caused a significant improvement, might’ve been client side.

**Comment by fkk-cz** [comment] 2022-05-20 23:37
Would you care to share what 'some security settings' includes for other people with this issue?

**Comment by Mynameisnotlenny** [comment] 2022-05-21 00:07
Gonna be honest not sure specifically what it was but my router has some ai security features and I cleared the caches for those and that seemed to fix it.

**Comment by fkk-cz** [comment] 2022-05-21 04:14
Closing this as it seems it's a player-specific problem.

**Closed by fkk-cz** 2022-05-21 04:14 UTC
