### ISSUE TITLE
My guns are not the correct mags 

### ISSUE THREAD

**Issue by blap1** [fkk-cz/noire-public#1086] opened 2022-07-31 23:17 UTC
I keep buying pistols which in default have 12 bullets in the mag like beretta and Springfield but i get 7 all the time how can i fix it?

**Comment by blap1** [comment] 2022-07-31 23:39
![FiveM® by Cfx re -  24  🎲 L A  Noire RP _ discord gg_noirerp _ Custom Cars   Handling   Sounds _ Active PD   EMS   DOT 8_1_2022 3_38_02 AM](https://user-images.githubusercontent.com/109044532/182050074-0d0db3e4-46e2-4059-8234-0e454ca95c51.png)

**Comment by blap1** [comment] 2022-08-01 21:29
????

**Comment by fkk-cz** [comment] 2022-08-08 08:31
Duplicate of #1092.

**Closed by fkk-cz** 2022-08-08 08:31 UTC
Labels: duplicate
