### ISSUE TITLE
LA Noire RP Concerns

### ISSUE THREAD

**Issue by echelon94** [fkk-cz/noire-public#1134] opened 2022-08-20 19:55 UTC
Hello I'd like to share my ideas for changes to LA Noire RP

- Seems that every admin on the server is a cop, they have enough power as it is, why not just stick to monitoring the server and having a civillian career so the other players on the server can rise the ranks of departments and manage them?

- Isa is an AMR Supervisor and also Highway patrol??? Thats 2 high quality whitelist jobs taken up by 1 person for no reason... She does Highway 99% of the time anyways so someone who is more passionate about AMR should take the entirety of the role. 

- Why are police cars able to achieve 200 MPH (Hellcat, etc?) If the cars in the server are too fast for robberies or other stuff, just create a better police system. If I rob a store on a bike I'm going to get away... There shouldn't be changes to the server or police cars because thats as realistic as it'll get.

- Why is UCL blacklisted by AMR? Just staff more people at the paleto highway. 
My biggest issue with this is that Cops and AMR hate going up to UCL or Paleto in general because they find the area toxic or whatever, this ruins the fun in everything, if you are AMR you should attend to the ENTIRE San Andreas, same with highway patrol... 

This is supposed to be fun and we get people that make blacklists or rules to make themselves more comfortable while ingame... Why are you trying to get comfortable in a GTA FiveM server... 

I feel like most people wake up skip brushing their teeth, and log right into LA Noire just to check on their buddies or post up at a location... I'm not judging this but it seems like all these recent changes are trying to make LA Noire "Realistic" as possible when 80% of LA Noire players dont even go outside to begin with so you wouldn't even know whats real or not...

If you've been on the computer everyday for the last 6-10 years, you wouldn't know what takes place in real life.

So since any of you don't know what realistic is, just focus on making the server fun as possible, and stop all this second-life nonsense.

**Comment by Bountyrogger** [comment] 2022-08-20 21:07
So a few things for you. Isa is still AMR Sup as well as SAHP as AMR is still trying to get into a place to have a strong leadership. She doesn't wanna drop AMR and watch it all fall apart. A good amount of AMR staff have only been with the Department for a month or maybe slightly more. You cant just hand someone a rank and say good luck. You need to train them to do the position correctly first. 

Second UCL is blacklisted was a decision by AMR Leadership. UCL has been blacklsited a total of 3 times. Each time is due to the fact that a large portion of people up there when we respond to calls just didn't value their life and on occasion the Medivac unit would be shot at when we came so we decided to Blacklist UCL calls. Unless decided otherwise this will not be changed.

**Comment by gxdsent** [comment] 2022-08-20 21:20
i sense no lies here. exactly why you see so many people end up leaving and not caring anymore bc of many of the reasons stated. the control is in a minute group of people’s hands who already are at the top of the food chain staff wise that effect the whole city whether it’s realized or not. whether it’s because people are ultimately outsmarting them (cops/highway/etc) or they can’t keep up (when people spend dozens upon dozens of hours to buy cars that shouldn’t be kept up with.) methods just have to be changed, not take the ability away from non law enforcement so that they can catch all the criminals when IF we’re talking realistically, in reality law enforcement can’t catch every person doing every crime, and which seems to be the problem is that if a common occurrence keeps happening in the criminal world then law enforcement/upper government cracks down on it and kills/nerfs the fun for civilians/criminals instead of coming together as law enforcement and coming up with ideas on how to prevent it from happening as much as it is. there are obviously things that can be abused bc of an overpowered car/bike/whatever but that can be changed but when every single advantage starts to favor one side of the city why else would people start to leave and/or get restless and start doing stupid shit ya feel me?

**Comment by echelon94** [comment] 2022-08-20 21:24
> So a few things for you. Isa is still AMR Sup as well as SAHP as AMR is still trying to get into a place to have a strong leadership. She doesn't wanna drop AMR and watch it all fall apart. A good amount of AMR staff have only been with the Department for a month or maybe slightly more. You cant just hand someone a rank and say good luck. You need to train them to do the position correctly first.
> 
> Second UCL is blacklisted was a decision by AMR Leadership. UCL has been blacklsited a total of 3 times. Each time is due to the fact that a large portion of people up there when we respond to calls just didn't value their life and on occasion the Medivac unit would be shot at when we came so we decided to Blacklist UCL calls. Unless decided otherwise this will not be changed.

She is waiting until AMR is fully trained? Bro it's a game, people not gonna play this for the rest of their life, people come and go and have real life changes. She's been double white listing for a long time and only spending about 30 mins on AMR per week.




> i sense no lies here. exactly why you see so many people end up leaving and not caring anymore bc of many of the reasons stated. the control is in a minute group of people’s hands who already are at the top of the food chain staff wise that effect the whole city whether it’s realized or not. whether it’s because people are ultimately outsmarting them (cops/highway/etc) or they can’t keep up (when people spend dozens upon dozens of hours to buy cars that shouldn’t be kept up with.) methods just have to be changed, not take the ability away from non law enforcement so that they can catch all the criminals when IF we’re talking realistically, in reality law enforcement can’t catch every person doing every crime, and which seems to be the problem is that if a common occurrence keeps happening in the criminal world then law enforcement/upper government cracks down on it and kills/nerfs the fun for civilians/criminals instead of coming together as law enforcement and coming up with ideas on how to prevent it from happening as much as it is. there are obviously things that can be abused bc of an overpowered car/bike/whatever but that can be changed but when every single advantage starts to favor one side of the city why else would people start to leave and/or get restless and start doing stupid shit ya feel me?

Facts... You got all the admins on the cop team and when all the bikes and hypercars escaping every robbery, they go OOC and say "we need to change the server files no way that should be like that"

**Comment by WaywardCanuck** [comment] 2022-08-20 21:42
Bro you joined github two hours ago just to complain about me!  I feel honoured! Did you want an autograph too?

**Comment by D4LPebble** [comment] 2022-08-20 21:48
i think the way this was approached was wrong but i cant say the opinion isnt valued.
some people are way too comfortable behind all the "power" or rank they hold. and everyone who is in these ranks will rub that statement off. some of these people have been here for so long and know the right people they feel they can just befriend the people who make decisions and stay "safe." 
now im not saying this is everyone with these ranks or even that these people are always acting this way. 
the admin team def leads towards PD, yes its more likely because the guy who puts these people in power is also HP. aint no shame in that. i think bitching about it isnt the way to go about it though, maybe throw in an idea that we would like some CIV/ other whitelist jobs in an admin position for the city so that when a PD admin has an opinion, other sides of the city have a different point or stance on things.
ALL crims have been in agreement for a long ass time that there is not enough types of crimes, or diversities in the way we can do crime (selling for example). so to us, its the same repetitive POWER hungry cops that want to win camping zones or being dicks charging way too much and being assholes. it happens though, thats the city and those people will come to justice. thats why we have captains like yush, and higherups in HP that will fire someone if need be. Admins are not a bad thing on PD, they should not handle their own issues for obvious reasons. But i can agree with you that the city needs admins that are not PD for an outside opinion. however, i dont think its going to give you a change you think it will. 
AMR blacklisting areas i agree is kinda a whack concept. gang territories or shootouts i can understand, but UCL should be met with HP force to aid the EMS there. EMS has not been the same since there used to be like 10 paramedics that would clock in at a time though. we only ever see a few clocking in at a time, sometimes 1 or 2 people which is NOT enough for a 260 person city. so maybe we can ENTICE people to want to BE AMR, like pay them more or anything of the sort.

bitching and complaining will get the city no where if you can not give a way to fix or make it better

**Comment by echelon94** [comment] 2022-08-20 21:52
> Bro you joined github two hours ago just to complain about me! I feel honoured! Did you want an autograph too?

When you speak North American English, it's spelled "honored"

**Comment by Competent1** [comment] 2022-08-20 21:52
I wish I didn't waste my time reading your "_ideas_". They suck. Based off your "_ideas_" (if that's what you want to call them), you obviously don't know what you're talking about. You should maybe do us a favor and keep these "_ideas_" to yourself next time.

**Comment by noyeahsure** [comment] 2022-08-20 21:54
> i think the way this was approached was wrong but i cant say the opinion isnt valued. some people are way too comfortable behind all the "power" or rank they hold. and everyone who is in these ranks will rub that statement off. some of these people have been here for so long and know the right people they feel they can just befriend the people who make decisions and stay "safe." now im not saying this is everyone with these ranks or even that these people are always acting this way. the admin team def leads towards PD, yes its more likely because the guy who puts these people in power is also HP. aint no shame in that. i think bitching about it isnt the way to go about it though, maybe throw in an idea that we would like some CIV/ other whitelist jobs in an admin position for the city so that when a PD admin has an opinion, other sides of the city have a different point or stance on things. ALL crims have been in agreement for a long ass time that there is not enough types of crimes, or diversities in the way we can do crime (selling for example). so to us, its the same repetitive POWER hungry cops that want to win camping zones or being dicks charging way too much and being assholes. it happens though, thats the city and those people will come to justice. thats why we have captains like yush, and higherups in HP that will fire someone if need be. Admins are not a bad thing on PD, they should not handle their own issues for obvious reasons. But i can agree with you that the city needs admins that are not PD for an outside opinion. however, i dont think its going to give you a change you think it will. AMR blacklisting areas i agree is kinda a whack concept. gang territories or shootouts i can understand, but UCL should be met with HP force to aid the EMS there. EMS has not been the same since there used to be like 10 paramedics that would clock in at a time though. we only ever see a few clocking in at a time, sometimes 1 or 2 people which is NOT enough for a 260 person city. so maybe we can ENTICE people to want to BE AMR, like pay them more or anything of the sort.
> 
> bitching and complaining will get the city no where if you can not give a way to fix or make it better

I completely agree with pebble here, the way this was approached was not good at all. if you wanna be heard, make and pitch ideas without the backhands and insults

**Comment by echelon94** [comment] 2022-08-20 21:54
> I wish I didn't waste my time reading your "_ideas_". They suck. Based off your "_ideas_" (if that's what you want to call them), you obviously don't know what you're talking about. You should maybe do us a favor and keep these "_ideas_" to yourself next time.

You haven't been outside in months kid LOL go learn a skill IRL and stop waiting ingame for the next party at the nightclub

**Comment by D4LPebble** [comment] 2022-08-20 21:55
yall just gonna bitch now and let a valid point go to waste and be a joke and itll never be adjusted

**Comment by okxeon** [comment] 2022-08-20 21:57
> "Why are police cars able to achieve 200 MPH (Hellcat, etc?)"

So what you are saying is the civ hellcat is ok to do 200 but the one on hp for catching speeders cant? Especially when everyone in here speeds down the highways in their hyper cars doing 200+. Because yes that makes sense. 

> "If the cars in the server are too fast for robberies or other stuff, just create a better police system."

What? This is equivalent to saying "if people are poor just print more money". 


Not sure who shit in your cheerios this morning, but if you want improvements suggest ideas on how to improve things - talking shit on the players and staff is just a waste of time on your end.

**Comment by echelon94** [comment] 2022-08-20 22:00
> > "Why are police cars able to achieve 200 MPH (Hellcat, etc?)"
> 
> So what you are saying is the civ hellcat is ok to do 200 but the one on hp for catching speeders cant? Especially when everyone in here speeds down the highways in their hyper cars doing 200+. Because yes that makes sense.
> 
> > "If the cars in the server are too fast for robberies or other stuff, just create a better police system."
> 
> What? This is equivalent to saying "if people are poor just print more money".
> 
> Not sure who shit in your cheerios this morning, but if you want improvements suggest ideas on how to improve things - talking shit on the players and staff is just a waste of time on your end.

Bro a Hellcat shouldn't be owned by a Highway Patrol Police Department, you dont see cops IRL patrolling in those bro...

IF cars are too fast for robberies, you get a more organized police system??? just like IRL bro... IRL you cant edit some server files and nerf stuff because you cant catch them. You'll apply more pressure, its very simple...

**Comment by BreezyEZ** [comment] 2022-08-20 22:09
Speaking of realism, since when do you ever see people IRL doing robberies in a fucking Ferrari, Lambo, you name it? Really seems like common sense isn't so common. Speaking in regards to HP and AMR on why we don't get to UCL,  half the time we go there we get swarmed by 20+ people that just ask the dumbest question, there to cop bait, or just be a pain in the ass. It happens everywhere, people see flashing lights and decide stop and step in and provide nothing to the RP scenario. Trust me cops don't really wanna be the "hardasses" you describe us as.. You be cool with us and provide a fun experience we do the same, but if you wanna be a complete dumbass we match that same energy.

**Comment by No-Yes1** [comment] 2022-08-20 22:13
I agree with the above, you're coming in here heated as fuck on a new account because you're too concerned with no revealing who you are. You are then being heated with anyone who questions you, telling them they haven't been outside and being disgruntled over what exactly?

**Comment by No-Yes1** [comment] 2022-08-20 22:14
Closing/Locking this due to just argumentative and no actual suggestion/feedback

**Comment by okxeon** [comment] 2022-08-20 22:14
> "IF cars are too fast for robberies, you get a more organized police system???"

Then give reasonable examples of what this means. If this is a "very simple" fix then it would have been done already.

**Closed** 2022-08-20 22:14 UTC
